// Auto-generated by scripts/generate-kanji-index.mjs - do not edit manually
import type { KanjiData } from '../../types/lookup.ts';

import kanji_0 from './kanji/一.json' with { type: 'json' };
import kanji_1 from './kanji/七.json' with { type: 'json' };
import kanji_2 from './kanji/万.json' with { type: 'json' };
import kanji_3 from './kanji/三.json' with { type: 'json' };
import kanji_4 from './kanji/上.json' with { type: 'json' };
import kanji_5 from './kanji/下.json' with { type: 'json' };
import kanji_6 from './kanji/中.json' with { type: 'json' };
import kanji_7 from './kanji/九.json' with { type: 'json' };
import kanji_8 from './kanji/事.json' with { type: 'json' };
import kanji_9 from './kanji/二.json' with { type: 'json' };
import kanji_10 from './kanji/五.json' with { type: 'json' };
import kanji_11 from './kanji/人.json' with { type: 'json' };
import kanji_12 from './kanji/今.json' with { type: 'json' };
import kanji_13 from './kanji/仕.json' with { type: 'json' };
import kanji_14 from './kanji/休.json' with { type: 'json' };
import kanji_15 from './kanji/会.json' with { type: 'json' };
import kanji_16 from './kanji/体.json' with { type: 'json' };
import kanji_17 from './kanji/何.json' with { type: 'json' };
import kanji_18 from './kanji/作.json' with { type: 'json' };
import kanji_19 from './kanji/使.json' with { type: 'json' };
import kanji_20 from './kanji/元.json' with { type: 'json' };
import kanji_21 from './kanji/兄.json' with { type: 'json' };
import kanji_22 from './kanji/先.json' with { type: 'json' };
import kanji_23 from './kanji/入.json' with { type: 'json' };
import kanji_24 from './kanji/八.json' with { type: 'json' };
import kanji_25 from './kanji/六.json' with { type: 'json' };
import kanji_26 from './kanji/円.json' with { type: 'json' };
import kanji_27 from './kanji/冬.json' with { type: 'json' };
import kanji_28 from './kanji/出.json' with { type: 'json' };
import kanji_29 from './kanji/分.json' with { type: 'json' };
import kanji_30 from './kanji/前.json' with { type: 'json' };
import kanji_31 from './kanji/力.json' with { type: 'json' };
import kanji_32 from './kanji/動.json' with { type: 'json' };
import kanji_33 from './kanji/北.json' with { type: 'json' };
import kanji_34 from './kanji/十.json' with { type: 'json' };
import kanji_35 from './kanji/千.json' with { type: 'json' };
import kanji_36 from './kanji/午.json' with { type: 'json' };
import kanji_37 from './kanji/半.json' with { type: 'json' };
import kanji_38 from './kanji/南.json' with { type: 'json' };
import kanji_39 from './kanji/友.json' with { type: 'json' };
import kanji_40 from './kanji/口.json' with { type: 'json' };
import kanji_41 from './kanji/古.json' with { type: 'json' };
import kanji_42 from './kanji/右.json' with { type: 'json' };
import kanji_43 from './kanji/名.json' with { type: 'json' };
import kanji_44 from './kanji/四.json' with { type: 'json' };
import kanji_45 from './kanji/国.json' with { type: 'json' };
import kanji_46 from './kanji/土.json' with { type: 'json' };
import kanji_47 from './kanji/地.json' with { type: 'json' };
import kanji_48 from './kanji/売.json' with { type: 'json' };
import kanji_49 from './kanji/変.json' with { type: 'json' };
import kanji_50 from './kanji/夏.json' with { type: 'json' };
import kanji_51 from './kanji/外.json' with { type: 'json' };
import kanji_52 from './kanji/多.json' with { type: 'json' };
import kanji_53 from './kanji/夜.json' with { type: 'json' };
import kanji_54 from './kanji/大.json' with { type: 'json' };
import kanji_55 from './kanji/天.json' with { type: 'json' };
import kanji_56 from './kanji/太.json' with { type: 'json' };
import kanji_57 from './kanji/女.json' with { type: 'json' };
import kanji_58 from './kanji/好.json' with { type: 'json' };
import kanji_59 from './kanji/妹.json' with { type: 'json' };
import kanji_60 from './kanji/姉.json' with { type: 'json' };
import kanji_61 from './kanji/始.json' with { type: 'json' };
import kanji_62 from './kanji/子.json' with { type: 'json' };
import kanji_63 from './kanji/字.json' with { type: 'json' };
import kanji_64 from './kanji/学.json' with { type: 'json' };
import kanji_65 from './kanji/安.json' with { type: 'json' };
import kanji_66 from './kanji/家.json' with { type: 'json' };
import kanji_67 from './kanji/寒.json' with { type: 'json' };
import kanji_68 from './kanji/小.json' with { type: 'json' };
import kanji_69 from './kanji/少.json' with { type: 'json' };
import kanji_70 from './kanji/山.json' with { type: 'json' };
import kanji_71 from './kanji/川.json' with { type: 'json' };
import kanji_72 from './kanji/左.json' with { type: 'json' };
import kanji_73 from './kanji/帰.json' with { type: 'json' };
import kanji_74 from './kanji/年.json' with { type: 'json' };
import kanji_75 from './kanji/広.json' with { type: 'json' };
import kanji_76 from './kanji/店.json' with { type: 'json' };
import kanji_77 from './kanji/弟.json' with { type: 'json' };
import kanji_78 from './kanji/弱.json' with { type: 'json' };
import kanji_79 from './kanji/強.json' with { type: 'json' };
import kanji_80 from './kanji/待.json' with { type: 'json' };
import kanji_81 from './kanji/後.json' with { type: 'json' };
import kanji_82 from './kanji/心.json' with { type: 'json' };
import kanji_83 from './kanji/思.json' with { type: 'json' };
import kanji_84 from './kanji/悪.json' with { type: 'json' };
import kanji_85 from './kanji/所.json' with { type: 'json' };
import kanji_86 from './kanji/手.json' with { type: 'json' };
import kanji_87 from './kanji/持.json' with { type: 'json' };
import kanji_88 from './kanji/教.json' with { type: 'json' };
import kanji_89 from './kanji/文.json' with { type: 'json' };
import kanji_90 from './kanji/新.json' with { type: 'json' };
import kanji_91 from './kanji/方.json' with { type: 'json' };
import kanji_92 from './kanji/日.json' with { type: 'json' };
import kanji_93 from './kanji/早.json' with { type: 'json' };
import kanji_94 from './kanji/明.json' with { type: 'json' };
import kanji_95 from './kanji/春.json' with { type: 'json' };
import kanji_96 from './kanji/昼.json' with { type: 'json' };
import kanji_97 from './kanji/時.json' with { type: 'json' };
import kanji_98 from './kanji/暑.json' with { type: 'json' };
import kanji_99 from './kanji/書.json' with { type: 'json' };
import kanji_100 from './kanji/月.json' with { type: 'json' };
import kanji_101 from './kanji/朝.json' with { type: 'json' };
import kanji_102 from './kanji/木.json' with { type: 'json' };
import kanji_103 from './kanji/本.json' with { type: 'json' };
import kanji_104 from './kanji/来.json' with { type: 'json' };
import kanji_105 from './kanji/東.json' with { type: 'json' };
import kanji_106 from './kanji/校.json' with { type: 'json' };
import kanji_107 from './kanji/楽.json' with { type: 'json' };
import kanji_108 from './kanji/母.json' with { type: 'json' };
import kanji_109 from './kanji/毎.json' with { type: 'json' };
import kanji_110 from './kanji/気.json' with { type: 'json' };
import kanji_111 from './kanji/水.json' with { type: 'json' };
import kanji_112 from './kanji/火.json' with { type: 'json' };
import kanji_113 from './kanji/父.json' with { type: 'json' };
import kanji_114 from './kanji/物.json' with { type: 'json' };
import kanji_115 from './kanji/犬.json' with { type: 'json' };
import kanji_116 from './kanji/生.json' with { type: 'json' };
import kanji_117 from './kanji/田.json' with { type: 'json' };
import kanji_118 from './kanji/男.json' with { type: 'json' };
import kanji_119 from './kanji/病.json' with { type: 'json' };
import kanji_120 from './kanji/白.json' with { type: 'json' };
import kanji_121 from './kanji/百.json' with { type: 'json' };
import kanji_122 from './kanji/目.json' with { type: 'json' };
import kanji_123 from './kanji/着.json' with { type: 'json' };
import kanji_124 from './kanji/知.json' with { type: 'json' };
import kanji_125 from './kanji/石.json' with { type: 'json' };
import kanji_126 from './kanji/社.json' with { type: 'json' };
import kanji_127 from './kanji/私.json' with { type: 'json' };
import kanji_128 from './kanji/秋.json' with { type: 'json' };
import kanji_129 from './kanji/空.json' with { type: 'json' };
import kanji_130 from './kanji/立.json' with { type: 'json' };
import kanji_131 from './kanji/終.json' with { type: 'json' };
import kanji_132 from './kanji/習.json' with { type: 'json' };
import kanji_133 from './kanji/者.json' with { type: 'json' };
import kanji_134 from './kanji/耳.json' with { type: 'json' };
import kanji_135 from './kanji/聞.json' with { type: 'json' };
import kanji_136 from './kanji/自.json' with { type: 'json' };
import kanji_137 from './kanji/花.json' with { type: 'json' };
import kanji_138 from './kanji/若.json' with { type: 'json' };
import kanji_139 from './kanji/行.json' with { type: 'json' };
import kanji_140 from './kanji/西.json' with { type: 'json' };
import kanji_141 from './kanji/見.json' with { type: 'json' };
import kanji_142 from './kanji/言.json' with { type: 'json' };
import kanji_143 from './kanji/話.json' with { type: 'json' };
import kanji_144 from './kanji/語.json' with { type: 'json' };
import kanji_145 from './kanji/読.json' with { type: 'json' };
import kanji_146 from './kanji/買.json' with { type: 'json' };
import kanji_147 from './kanji/赤.json' with { type: 'json' };
import kanji_148 from './kanji/足.json' with { type: 'json' };
import kanji_149 from './kanji/車.json' with { type: 'json' };
import kanji_150 from './kanji/近.json' with { type: 'json' };
import kanji_151 from './kanji/週.json' with { type: 'json' };
import kanji_152 from './kanji/道.json' with { type: 'json' };
import kanji_153 from './kanji/遠.json' with { type: 'json' };
import kanji_154 from './kanji/重.json' with { type: 'json' };
import kanji_155 from './kanji/金.json' with { type: 'json' };
import kanji_156 from './kanji/長.json' with { type: 'json' };
import kanji_157 from './kanji/閉.json' with { type: 'json' };
import kanji_158 from './kanji/開.json' with { type: 'json' };
import kanji_159 from './kanji/間.json' with { type: 'json' };
import kanji_160 from './kanji/雨.json' with { type: 'json' };
import kanji_161 from './kanji/電.json' with { type: 'json' };
import kanji_162 from './kanji/青.json' with { type: 'json' };
import kanji_163 from './kanji/食.json' with { type: 'json' };
import kanji_164 from './kanji/飲.json' with { type: 'json' };
import kanji_165 from './kanji/駅.json' with { type: 'json' };
import kanji_166 from './kanji/高.json' with { type: 'json' };
import kanji_167 from './kanji/魚.json' with { type: 'json' };
import kanji_168 from './kanji/鳥.json' with { type: 'json' };

export const ALL_KANJI: KanjiData[] = [
  kanji_0 as unknown as KanjiData,
  kanji_1 as unknown as KanjiData,
  kanji_2 as unknown as KanjiData,
  kanji_3 as unknown as KanjiData,
  kanji_4 as unknown as KanjiData,
  kanji_5 as unknown as KanjiData,
  kanji_6 as unknown as KanjiData,
  kanji_7 as unknown as KanjiData,
  kanji_8 as unknown as KanjiData,
  kanji_9 as unknown as KanjiData,
  kanji_10 as unknown as KanjiData,
  kanji_11 as unknown as KanjiData,
  kanji_12 as unknown as KanjiData,
  kanji_13 as unknown as KanjiData,
  kanji_14 as unknown as KanjiData,
  kanji_15 as unknown as KanjiData,
  kanji_16 as unknown as KanjiData,
  kanji_17 as unknown as KanjiData,
  kanji_18 as unknown as KanjiData,
  kanji_19 as unknown as KanjiData,
  kanji_20 as unknown as KanjiData,
  kanji_21 as unknown as KanjiData,
  kanji_22 as unknown as KanjiData,
  kanji_23 as unknown as KanjiData,
  kanji_24 as unknown as KanjiData,
  kanji_25 as unknown as KanjiData,
  kanji_26 as unknown as KanjiData,
  kanji_27 as unknown as KanjiData,
  kanji_28 as unknown as KanjiData,
  kanji_29 as unknown as KanjiData,
  kanji_30 as unknown as KanjiData,
  kanji_31 as unknown as KanjiData,
  kanji_32 as unknown as KanjiData,
  kanji_33 as unknown as KanjiData,
  kanji_34 as unknown as KanjiData,
  kanji_35 as unknown as KanjiData,
  kanji_36 as unknown as KanjiData,
  kanji_37 as unknown as KanjiData,
  kanji_38 as unknown as KanjiData,
  kanji_39 as unknown as KanjiData,
  kanji_40 as unknown as KanjiData,
  kanji_41 as unknown as KanjiData,
  kanji_42 as unknown as KanjiData,
  kanji_43 as unknown as KanjiData,
  kanji_44 as unknown as KanjiData,
  kanji_45 as unknown as KanjiData,
  kanji_46 as unknown as KanjiData,
  kanji_47 as unknown as KanjiData,
  kanji_48 as unknown as KanjiData,
  kanji_49 as unknown as KanjiData,
  kanji_50 as unknown as KanjiData,
  kanji_51 as unknown as KanjiData,
  kanji_52 as unknown as KanjiData,
  kanji_53 as unknown as KanjiData,
  kanji_54 as unknown as KanjiData,
  kanji_55 as unknown as KanjiData,
  kanji_56 as unknown as KanjiData,
  kanji_57 as unknown as KanjiData,
  kanji_58 as unknown as KanjiData,
  kanji_59 as unknown as KanjiData,
  kanji_60 as unknown as KanjiData,
  kanji_61 as unknown as KanjiData,
  kanji_62 as unknown as KanjiData,
  kanji_63 as unknown as KanjiData,
  kanji_64 as unknown as KanjiData,
  kanji_65 as unknown as KanjiData,
  kanji_66 as unknown as KanjiData,
  kanji_67 as unknown as KanjiData,
  kanji_68 as unknown as KanjiData,
  kanji_69 as unknown as KanjiData,
  kanji_70 as unknown as KanjiData,
  kanji_71 as unknown as KanjiData,
  kanji_72 as unknown as KanjiData,
  kanji_73 as unknown as KanjiData,
  kanji_74 as unknown as KanjiData,
  kanji_75 as unknown as KanjiData,
  kanji_76 as unknown as KanjiData,
  kanji_77 as unknown as KanjiData,
  kanji_78 as unknown as KanjiData,
  kanji_79 as unknown as KanjiData,
  kanji_80 as unknown as KanjiData,
  kanji_81 as unknown as KanjiData,
  kanji_82 as unknown as KanjiData,
  kanji_83 as unknown as KanjiData,
  kanji_84 as unknown as KanjiData,
  kanji_85 as unknown as KanjiData,
  kanji_86 as unknown as KanjiData,
  kanji_87 as unknown as KanjiData,
  kanji_88 as unknown as KanjiData,
  kanji_89 as unknown as KanjiData,
  kanji_90 as unknown as KanjiData,
  kanji_91 as unknown as KanjiData,
  kanji_92 as unknown as KanjiData,
  kanji_93 as unknown as KanjiData,
  kanji_94 as unknown as KanjiData,
  kanji_95 as unknown as KanjiData,
  kanji_96 as unknown as KanjiData,
  kanji_97 as unknown as KanjiData,
  kanji_98 as unknown as KanjiData,
  kanji_99 as unknown as KanjiData,
  kanji_100 as unknown as KanjiData,
  kanji_101 as unknown as KanjiData,
  kanji_102 as unknown as KanjiData,
  kanji_103 as unknown as KanjiData,
  kanji_104 as unknown as KanjiData,
  kanji_105 as unknown as KanjiData,
  kanji_106 as unknown as KanjiData,
  kanji_107 as unknown as KanjiData,
  kanji_108 as unknown as KanjiData,
  kanji_109 as unknown as KanjiData,
  kanji_110 as unknown as KanjiData,
  kanji_111 as unknown as KanjiData,
  kanji_112 as unknown as KanjiData,
  kanji_113 as unknown as KanjiData,
  kanji_114 as unknown as KanjiData,
  kanji_115 as unknown as KanjiData,
  kanji_116 as unknown as KanjiData,
  kanji_117 as unknown as KanjiData,
  kanji_118 as unknown as KanjiData,
  kanji_119 as unknown as KanjiData,
  kanji_120 as unknown as KanjiData,
  kanji_121 as unknown as KanjiData,
  kanji_122 as unknown as KanjiData,
  kanji_123 as unknown as KanjiData,
  kanji_124 as unknown as KanjiData,
  kanji_125 as unknown as KanjiData,
  kanji_126 as unknown as KanjiData,
  kanji_127 as unknown as KanjiData,
  kanji_128 as unknown as KanjiData,
  kanji_129 as unknown as KanjiData,
  kanji_130 as unknown as KanjiData,
  kanji_131 as unknown as KanjiData,
  kanji_132 as unknown as KanjiData,
  kanji_133 as unknown as KanjiData,
  kanji_134 as unknown as KanjiData,
  kanji_135 as unknown as KanjiData,
  kanji_136 as unknown as KanjiData,
  kanji_137 as unknown as KanjiData,
  kanji_138 as unknown as KanjiData,
  kanji_139 as unknown as KanjiData,
  kanji_140 as unknown as KanjiData,
  kanji_141 as unknown as KanjiData,
  kanji_142 as unknown as KanjiData,
  kanji_143 as unknown as KanjiData,
  kanji_144 as unknown as KanjiData,
  kanji_145 as unknown as KanjiData,
  kanji_146 as unknown as KanjiData,
  kanji_147 as unknown as KanjiData,
  kanji_148 as unknown as KanjiData,
  kanji_149 as unknown as KanjiData,
  kanji_150 as unknown as KanjiData,
  kanji_151 as unknown as KanjiData,
  kanji_152 as unknown as KanjiData,
  kanji_153 as unknown as KanjiData,
  kanji_154 as unknown as KanjiData,
  kanji_155 as unknown as KanjiData,
  kanji_156 as unknown as KanjiData,
  kanji_157 as unknown as KanjiData,
  kanji_158 as unknown as KanjiData,
  kanji_159 as unknown as KanjiData,
  kanji_160 as unknown as KanjiData,
  kanji_161 as unknown as KanjiData,
  kanji_162 as unknown as KanjiData,
  kanji_163 as unknown as KanjiData,
  kanji_164 as unknown as KanjiData,
  kanji_165 as unknown as KanjiData,
  kanji_166 as unknown as KanjiData,
  kanji_167 as unknown as KanjiData,
  kanji_168 as unknown as KanjiData,
];

export const KANJI_MAP: Map<string, KanjiData> = new Map(
  ALL_KANJI.map((k) => [k.character, k])
);
